env:
  browser: true
  es2021: true
  node: true
  jest: true

extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module

globals:
  expect: "readonly"

overrides:
  - files:
      - "**/*.spec.js"
      - "**/*.spec.jsx"
    env:
      jest: true
