name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'  
          cache-dependency-path: functions/package-lock.json
      - run: |
              npm install
              npm run build --if-present
              npm run test --if-present
