name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2

      - run: |
          cd server
          touch .env
          echo NODE_ENV=${{ vars.NODE_ENV }} >> .env
          npm install
          npm run build --if-present
          npm run test  --if-present
<<<<<<< HEAD
          cd ../client
          npm install
          npm run build --if-present

      # Add ESLint setup
      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Create ESLint configuration
        run: npx eslint --init

      # Run ESLint with --fix and --quiet flags
      - name: Run ESLint
        run: npx eslint --fix --quiet .
=======
  front-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2

      - run: |
          cd client
          npm install
          CI="" npm run build --if-present
          npm run test  --if-present
  
>>>>>>> b76be32546a1c5f56f692c06d63a5205fa1bf05e
