name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2 
      
      - run: |
              cd server
              touch .env
              echo NODE_ENV=${{ vars.NODE_ENV }} >> .env
              npm install
              npm run build --if-present
              npm run test  --if-present
      